spring.application.name=tasks
spring.datasource.url=jdbc:postgresql://localhost:5432/taskts
spring.datasource.username=khalilbentouda
spring.datasource.password=""
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true
spring.jpa.database=postgresql
spring.jpa.hibernate.ddl-auto=update
server.port = 9090

security.jwt.secret-key=Ep57Qaqo+n5FlcqIzs+O59Y58d7ydah+TtLyW2IIbD8=
security.jwt.expiration-time=3600000

#logging.level.org.springframework.security=trace